name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  init-test-action:
    name: Init GitHub Action Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          [
            to-include-1.txt,
            to-include-2.txt,
            to-exclude-1.txt,
            to-exclude-2.txt
          ]

    steps:
      - name: Create file to archive
        run: |
          mkdir -p output
          date > output/${{ matrix.file }}

      - name: Archive file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: output/${{ matrix.file }}

  test-action:
    needs: [init-test-action]
    name: GitHub Action Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          includes: |
            to-include-1.txt
            to-include-2.txt
          excludes: |
            to-exclude-1.txt
            to-exclude-2.txt

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.deleted-artifacts }}"
